[package]
name = "root_exec"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
error-chain = "0.10.0"
libc = "0.2.23"
log = "0.3.8"
log4rs = "0.7.0"
serde = "1.0.8"
serde_derive = "1.0.8"
simple_logger = "0.4.0"
structopt = "0.0.3"
structopt-derive = "0.0.3"
